### ISSUE TITLE
nested arrays and maps

### ISSUE THREAD

**Issue by vird** [madfish-solutions/sol2ligo#113]

**Comment by konchunas** [comment]
Solidity code 
```solidity
uint x = twodim[0][1];
```

translates to 

```
const x : nat = (case (case self.twodim[0n] of | None -> (map end : map(nat, nat)) | Some(x) -> x end)[1n] of | None -> 0n | Some(x) -> x end);
```

Which is semantically correct. But LIGO parse is not yet able to parse `(case __ end)[1n]` due to `Parse error in file "Test.ligo", line 20, characters 106-107 at "[", after ")"`

Relevant bug report and discussion: https://gitlab.com/ligolang/ligo/-/issues/154
